# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmplateConsumer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmplateConsumer
  
  
  # For Networking
  pod 'Moya'
  
  # For load images
  pod 'Kingfisher'
  
  # For Progress Loader
  pod 'NVActivityIndicatorView'
  

  target 'EmplateConsumerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmplateConsumerUITests' do
    inherit! :complete
    # Pods for testing
  end

end
